export const products = [
  {
    id: "1",
    productName: "Rose Water Hydrating Face Mist",
    productImage: "/images/productEx.png",
    brand: "Botanical Glow",
    category: "Skincare",
    originalPrice: 24.99,
    discountPrice: 19.99,
    isOnSale: true,
    description: `A refreshing facial mist infused with pure rose water to hydrate and soothe the skin. Perfect for daily use, it helps reduce redness and adds a natural glow.`,
  },
  {
    id: "2",
    productName: "Velvet Matte Lipstick",
    productImage: "/images/productEx.png",
    brand: "LuxeCharm",
    category: "Makeup",
    originalPrice: 16.5,
    discountPrice: 12.9,
    isOnSale: true,
    description: `This creamy matte lipstick delivers intense color payoff with a soft, lightweight feel. Long-lasting and comfortable, it keeps your lips smooth all day.`,
  },
  {
    id: "3",
    productName: "Argan Oil Repair Hair Serum",
    productImage: "/images/productEx.png",
    brand: "SilkEssence",
    category: "Haircare",
    originalPrice: 32.0,
    discountPrice: 32.0,
    isOnSale: false,
    description: `A nutrient-rich serum formulated with pure argan oil to repair dry and damaged hair. It adds shine, reduces frizz, and leaves your hair silky smooth.`,
  },
  {
    id: "4",
    productName: "Soothing Aloe Vera Gel",
    productImage: "/images/productEx.png",
    brand: "PureRadiance",
    category: "Skincare",
    originalPrice: 18.75,
    discountPrice: 14.99,
    isOnSale: true,
    description: `This multipurpose gel calms irritated skin and provides instant hydration. Made with natural aloe vera, it absorbs quickly without leaving sticky residue.`,
  },
  {
    id: "5",
    productName: "Lavender Shea Body Lotion",
    productImage: "/images/productEx.png",
    brand: "CalmNest",
    category: "Bodycare",
    originalPrice: 21.0,
    discountPrice: 21.0,
    isOnSale: false,
    description: `A luxurious body lotion blended with shea butter and lavender extract for deep hydration. It softens the skin and leaves a relaxing scent that lasts.`,
  },
  {
    id: "6",
    productName: "Coconut Moisture Hair Mask",
    productImage: "/images/productEx.png",
    brand: "TropiSilk",
    category: "Haircare",
    originalPrice: 27.5,
    discountPrice: 22.0,
    isOnSale: true,
    description: `Restore dry, brittle hair with this ultra-moisturizing coconut-based mask. It penetrates deeply to nourish each strand and boost overall hair health.`,
  },
  {
    id: "7",
    productName: "Citrus Refresh Body Wash",
    productImage: "/images/productEx.png",
    brand: "FreshAura",
    category: "Bodycare",
    originalPrice: 14.25,
    discountPrice: 14.25,
    isOnSale: false,
    description: `Energize your shower routine with this zesty citrus body wash. It gently cleanses the skin while leaving it soft, refreshed, and revitalized.`,
  },
  {
    id: "8",
    productName: "Radiant Glow Highlighter Palette",
    productImage: "/images/productEx.png",
    brand: "GlamVibe",
    category: "Makeup",
    originalPrice: 28.9,
    discountPrice: 24.5,
    isOnSale: true,
    description: `This highlighter palette features three luminous shades for a customizable glow. Its silky texture blends effortlessly to enhance your natural features.`,
  },
  {
    id: "9",
    productName: "Refreshing Green Tea Toner",
    productImage: "/images/productEx.png",
    brand: "Leaf&Bloom",
    category: "Skincare",
    originalPrice: 19.0,
    discountPrice: 15.5,
    isOnSale: true,
    description: `A gentle toner enriched with green tea extract to balance and purify the skin. It minimizes pores and provides lightweight hydration without irritation.`,
  },
  {
    id: "10",
    productName: "Soft Touch Beauty Blender",
    productImage: "/images/productEx.png",
    brand: "Blendify",
    category: "Beauty Tools",
    originalPrice: 9.99,
    discountPrice: 9.99,
    isOnSale: false,
    description: `This soft, latex-free beauty blender blends makeup seamlessly for a flawless finish. Its teardrop shape allows precise application in all areas of the face.`,
  },
  {
    id: "11",
    productName: "Silky Night Repair Face Cream",
    productImage: "/images/productEx.png",
    brand: "MoonDew",
    category: "Skincare",
    originalPrice: 35.0,
    discountPrice: 29.5,
    isOnSale: true,
    description: `An intensive night cream that deeply nourishes and repairs the skin while you sleep. It reduces fine lines and improves elasticity for a youthful glow.`,
  },
  {
    id: "12",
    productName: "Berry Tint Lip Balm",
    productImage: "/images/productEx.png",
    brand: "SweetLips",
    category: "Makeup",
    originalPrice: 8.5,
    discountPrice: 8.5,
    isOnSale: false,
    description: `A hydrating lip balm with a sheer berry tint for a natural pop of color. It softens and protects the lips with nourishing botanical oils.`,
  },
  {
    id: "13",
    productName: "Nourish & Shine Hair Oil",
    productImage: "/images/productEx.png",
    brand: "GlowStrand",
    category: "Haircare",
    originalPrice: 25.0,
    discountPrice: 20.0,
    isOnSale: true,
    description: `Lightweight yet powerful, this hair oil tames frizz and adds brilliant shine. It absorbs quickly without weighing the hair down.`,
  },
  {
    id: "14",
    productName: "Vanilla Orchid Body Butter",
    productImage: "/images/productEx.png",
    brand: "SilkWhip",
    category: "Bodycare",
    originalPrice: 23.5,
    discountPrice: 23.5,
    isOnSale: false,
    description: `This rich body butter melts into the skin, providing long-lasting moisture. The warm vanilla orchid scent creates a calming and luxurious experience.`,
  },
  {
    id: "15",
    productName: "Blossom Breeze Eau de Parfum",
    productImage: "/images/productEx.png",
    brand: "Scentelier",
    category: "Fragrance",
    originalPrice: 48.0,
    discountPrice: 38.0,
    isOnSale: true,
    description: `A delicate floral perfume with notes of jasmine and peony for an elegant aroma. Long-lasting and feminine, it’s perfect for day or night.`,
  },
  {
    id: "16",
    productName: "Amber Wood Perfume Mist",
    productImage: "/images/productEx.png",
    brand: "MystiScents",
    category: "Fragrance",
    originalPrice: 30.0,
    discountPrice: 30.0,
    isOnSale: false,
    description: `A warm, woody mist with hints of amber and vanilla for a cozy, sophisticated scent. Lightweight and versatile, ideal for daily wear.`,
  },
  {
    id: "17",
    productName: "Precision Brow Pencil",
    productImage: "/images/productEx.png",
    brand: "ArchCraft",
    category: "Makeup",
    originalPrice: 12.75,
    discountPrice: 10.5,
    isOnSale: true,
    description: `This ultra-fine brow pencil allows precise shaping and filling for natural-looking brows. The smudge-proof formula ensures long-lasting definition.`,
  },
  {
    id: "18",
    productName: "Hydrating Sheet Mask Set",
    productImage: "/images/productEx.png",
    brand: "AquaBloom",
    category: "Skincare",
    originalPrice: 17.0,
    discountPrice: 17.0,
    isOnSale: false,
    description: `A set of ultra-hydrating sheet masks infused with botanical extracts. Each mask delivers deep moisture and leaves the skin plump and glowing.`,
  },
  {
    id: "19",
    productName: "Classic Paddle Hair Brush",
    productImage: "/images/productEx.png",
    brand: "TameTress",
    category: "Beauty Tools",
    originalPrice: 15.0,
    discountPrice: 12.0,
    isOnSale: true,
    description: `This durable paddle brush gently detangles hair without causing breakage. Its wide surface makes styling quick, smooth, and effortless.`,
  },
  {
    id: "20",
    productName: "Rose Gold Eyelash Curler",
    productImage: "/images/productEx.png",
    brand: "LashLuxe",
    category: "Beauty Tools",
    originalPrice: 11.25,
    discountPrice: 11.25,
    isOnSale: false,
    description: `A sleek, rose gold eyelash curler designed to lift and curl lashes with ease. The ergonomic handle provides comfort and precision in every use.`,
  },
];
