export const products = [
  {
    id: "1",
    productName: "Rose Water Hydrating Face Mist",
    slug: "Rose-Water-Hydrating-Face-Mist",
    productImage: "/images/productEx4.png",
    brand: "Botanical Glow",
    category: "Skincare (Face)",
    price: 24.99,
    isOnSale: true,
    description: `A refreshing facial mist infused with pure rose water to hydrate and soothe the skin. Perfect for daily use, it helps reduce redness and adds a natural glow.`,
  },
  {
    id: "2",
    productName: "Velvet Matte Lipstick",
    slug: "Velvet-Matte-Lipstick",
    productImage: "/images/productEx2.png",
    brand: "LuxeCharm",
    category: "Makeup",
    price: 16.5,
    isOnSale: true,
    description: `This creamy matte lipstick delivers intense color payoff with a soft, lightweight feel. Long-lasting and comfortable, it keeps your lips smooth all day.`,
  },
  {
    id: "3",
    productName: "Argan Oil Repair Hair Serum",
    slug: "Argan-Oil-Repair-Hair-Serum",
    productImage: "/images/productEx3.png",
    brand: "SilkEssence",
    category: "Hair Care",
    price: 32.0,
    isOnSale: false,
    description: `A nutrient-rich serum formulated with pure argan oil to repair dry and damaged hair. It adds shine, reduces frizz, and leaves your hair silky smooth.`,
  },
  {
    id: "4",
    productName: "Soothing Aloe Vera Gel",
    slug: "Soothing-Aloe-Vera-Gel",
    productImage: "/images/productEx.png",
    brand: "PureRadiance",
    category: "Skincare (Face)",
    price: 1800.75,
    isOnSale: true,
    description: `This multipurpose gel calms irritated skin and provides instant hydration. Made with natural aloe vera, it absorbs quickly without leaving sticky residue.`,
  },
  {
    id: "5",
    productName: "Lavender Shea Body Lotion",
    slug: "Lavender-Shea-Body-Lotion",
    productImage: "/images/productEx5.png",
    brand: "CalmNest",
    category: "Body Care",
    price: 21.0,
    isOnSale: false,
    description: `A luxurious body lotion blended with shea butter and lavender extract for deep hydration. It softens the skin and leaves a relaxing scent that lasts.`,
  },
  {
    id: "6",
    productName: "Coconut Moisture Hair Mask",
    slug: "Coconut-Moisture-Hair-Mask",
    productImage: "/images/productEx7.png",
    brand: "TropiSilk",
    category: "Hair Care",
    price: 27000.5,
    isOnSale: true,
    description: `Restore dry, brittle hair with this ultra-moisturizing coconut-based mask. It penetrates deeply to nourish each strand and boost overall hair health.`,
  },
  {
    id: "7",
    productName: "Citrus Refresh Body Wash",
    slug: "Citrus-Refresh-Body-Wash",
    productImage: "/images/productEx7.png",
    brand: "FreshAura",
    category: "Body Care",
    price: 14000.0,
    isOnSale: false,
    description: `Energize your shower routine with this zesty citrus body wash. It gently cleanses the skin while leaving it soft, refreshed, and revitalized.`,
  },
  {
    id: "8",
    productName: "Radiant Glow Highlighter Palette",
    slug: "Radiant-Glow-Highlighter-Palette",
    productImage: "/images/productEx8.png",
    brand: "GlamVibe",
    category: "Makeup",
    price: 2800.9,
    isOnSale: true,
    description: `This highlighter palette features three luminous shades for a customizable glow. Its silky texture blends effortlessly to enhance your natural features.`,
  },
  {
    id: "9",
    productName: "Refreshing Green Tea Toner",
    slug: "Refreshing-Green-Tea-Toner",
    productImage: "/images/productEx6.png",
    brand: "Leaf&Bloom",
    category: "Skincare (Face)",
    price: 19.0,
    isOnSale: true,
    description: `A gentle toner enriched with green tea extract to balance and purify the skin. It minimizes pores and provides lightweight hydration without irritation.`,
  },
  {
    id: "10",
    productName: "Soft Touch Beauty Blender",
    slug: "Soft-Touch-Beauty-Blender",
    productImage: "/images/productEx2.png",
    brand: "Blendify",
    category: "Beauty Tools",
    price: 9.99,
    isOnSale: false,
    description: `This soft, latex-free beauty blender blends makeup seamlessly for a flawless finish. Its teardrop shape allows precise application in all areas of the face.`,
  },
  {
    id: "11",
    productName: "Silky Night Repair Face Cream",
    slug: "Silky-Night-Repair-Face-Cream",
    productImage: "/images/productEx3.png",
    brand: "MoonDew",
    category: "Skincare (Face)",
    price: 35.0,
    isOnSale: true,
    description: `An intensive night cream that deeply nourishes and repairs the skin while you sleep. It reduces fine lines and improves elasticity for a youthful glow.`,
  },
  {
    id: "12",
    productName: "Berry Tint Lip Balm",
    slug: "Berry-Tint-Lip-Balm",
    productImage: "/images/productEx5.png",
    brand: "SweetLips",
    category: "Makeup",
    price: 8.5,
    isOnSale: false,
    description: `A hydrating lip balm with a sheer berry tint for a natural pop of color. It softens and protects the lips with nourishing botanical oils.`,
  },
  {
    id: "13",
    productName: "Nourish & Shine Hair Oil",
    slug: "Nourish-&-Shine-Hair-Oil",
    productImage: "/images/productEx8.png",
    brand: "GlowStrand",
    category: "Hair Care",
    price: 25.0,
    isOnSale: true,
    description: `Lightweight yet powerful, this hair oil tames frizz and adds brilliant shine. It absorbs quickly without weighing the hair down.`,
  },
  {
    id: "14",
    productName: "Vanilla Orchid Body Butter",
    slug: "Vanilla-Orchid-Body-Butter",
    productImage: "/images/productEx6.png",
    brand: "SilkWhip",
    category: "Body Care",
    price: 23.5,
    isOnSale: false,
    description: `This rich body butter melts into the skin, providing long-lasting moisture. The warm vanilla orchid scent creates a calming and luxurious experience.`,
  },
  {
    id: "15",
    productName: "Blossom Breeze Eau de Parfum",
    slug: "Blossom-Breeze-Eau-de-Parfum",
    productImage: "/images/productEx7.png",
    brand: "Scentelier",
    category: "Fragrance",
    price: 48.0,
    isOnSale: true,
    description: `A delicate floral perfume with notes of jasmine and peony for an elegant aroma. Long-lasting and feminine, it’s perfect for day or night.`,
  },
  {
    id: "16",
    productName: "Amber Wood Perfume Mist",
    slug: "Amber-Wood-Perfume-Mist",
    productImage: "/images/productEx8.png",
    brand: "MystiScents",
    category: "Fragrance",
    price: 30.0,
    isOnSale: false,
    description: `A warm, woody mist with hints of amber and vanilla for a cozy, sophisticated scent. Lightweight and versatile, ideal for daily wear.`,
  },
  {
    id: "17",
    productName: "Precision Brow Pencil",
    slug: "Precision-Brow-Pencil",
    productImage: "/images/productEx7.png",
    brand: "ArchCraft",
    category: "Makeup",
    price: 12.75,
    isOnSale: true,
    description: `This ultra-fine brow pencil allows precise shaping and filling for natural-looking brows. The smudge-proof formula ensures long-lasting definition.`,
  },
  {
    id: "18",
    productName: "Hydrating Sheet Mask Set",
    slug: "Hydrating-Sheet-Mask-Set",
    productImage: "/images/productEx.png",
    brand: "AquaBloom",
    category: "Skincare (Face)",
    price: 17.0,
    isOnSale: false,
    description: `A set of ultra-hydrating sheet masks infused with botanical extracts. Each mask delivers deep moisture and leaves the skin plump and glowing.`,
  },
  {
    id: "19",
    productName: "Classic Paddle Hair Brush",
    slug: "Classic-Paddle-Hair-Brush",
    productImage: "/images/productEx2.png",
    brand: "TameTress",
    category: "Fragrance",
    price: 15.0,
    isOnSale: true,
    description: `This durable paddle brush gently detangles hair without causing breakage. Its wide surface makes styling quick, smooth, and effortless.`,
  },
  {
    id: "20",
    productName: "Rose Gold Eyelash Curler",
    slug: "Rose-Gold-Eyelash-Curler",
    productImage: "/images/productEx2.png",
    brand: "LashLuxe",
    category: "Beauty Tools",
    price: 11.25,
    isOnSale: false,
    description: `A sleek, rose gold eyelash curler designed to lift and curl lashes with ease. The ergonomic handle provides comfort and precision in every use.`,
  },
  {
    id: "21",
    productName: "HydraGlow Vitamin C Serum",
    slug: "HydraGlow-Vitamin-C-Serum",
    productImage: "/images/productEx3.png",
    brand: "LumiSkin",
    category: "Skincare (Face)",
    price: 34.99,
    isOnSale: true,
    description: `A brightening serum infused with Vitamin C to even skin tone and restore radiance. Its lightweight formula absorbs quickly, leaving your skin refreshed and glowing.`,
  },
  {
    id: "22",
    productName: "Velvet Finish Setting Spray",
    slug: "Velvet-Finish-Setting-Spray",
    productImage: "/images/productEx4.png",
    brand: "GlowFix",
    category: "Makeup",
    price: 19.5,
    isOnSale: false,
    description: `A weightless mist that locks in makeup for a long-lasting, matte finish. It hydrates while keeping excess oil at bay throughout the day.`,
  },
  {
    id: "23",
    productName: "Keratin Smooth Shampoo",
    slug: "Keratin-Smooth-Shampoo",
    productImage: "/images/productEx5.png",
    brand: "SilkTreat",
    category: "Hair Care",
    price: 22.0,
    isOnSale: true,
    description: `Formulated with keratin protein, this shampoo gently cleanses and strengthens hair. It leaves strands smooth, manageable, and frizz-free.`,
  },
  {
    id: "24",
    productName: "Vanilla Bean Body Scrub",
    slug: "Vanilla-Bean-Body-Scrub",
    productImage: "/images/productEx6.png",
    brand: "SugarBloom",
    category: "Body Care",
    price: 20.0,
    isOnSale: false,
    description: `An exfoliating body scrub enriched with vanilla and natural sugar crystals. It polishes dull skin, leaving it silky smooth and delicately scented.`,
  },
  {
    id: "25",
    productName: "Precision Contour Brush",
    slug: "Precision-Contour-Brush",
    productImage: "/images/productEx7.png",
    brand: "Blendify",
    category: "Fragrance",
    price: 12.99,
    isOnSale: true,
    description: `This angled contour brush provides perfect control for sculpting and defining features. Its soft bristles blend seamlessly for a professional finish.`,
  },
  {
    id: "26",
    productName: "Peony Dream Eau de Parfum",
    slug: "Peony-Dream-Eau-de-Parfum",
    productImage: "/images/productEx8.png",
    brand: "AromaLuxe",
    category: "Fragrance",
    price: 52.0,
    isOnSale: true,
    description: `A romantic fragrance featuring notes of peony, rose, and sandalwood. This elegant perfume captures the essence of timeless femininity.`,
  },
  {
    id: "27",
    productName: "Charcoal Detox Clay Mask",
    slug: "Charcoal-Detox-Clay-Mask",
    productImage: "/images/productEx2.png",
    brand: "PureZen",
    category: "Skincare (Face)",
    price: 26.75,
    isOnSale: false,
    description: `A deep-cleansing mask that draws out impurities and excess oil using activated charcoal. Leaves the skin purified and refreshed without over-drying.`,
  },
  {
    id: "28",
    productName: "Creamy Nude Lip Gloss",
    slug: "Creamy-Nude-Lip-Gloss",
    productImage: "/images/productEx3.png",
    brand: "LushTint",
    category: "Makeup",
    price: 14.99,
    isOnSale: true,
    description: `A glossy nude lip color enriched with shea butter for moisture and shine. Perfect for everyday wear with a non-sticky finish.`,
  },
  {
    id: "29",
    productName: "Coconut Curl Defining Cream",
    slug: "Coconut-Curl-Defining-Cream",
    productImage: "/images/productEx.png",
    brand: "WaveMuse",
    category: "Hair Care",
    price: 24.0,
    isOnSale: true,
    description: `Define and nourish your curls with this rich coconut cream. It reduces frizz and enhances natural texture for soft, bouncy curls.`,
  },
  {
    id: "30",
    productName: "Honey Almond Body Oil",
    slug: "Honey-Almond-Body-Oil",
    productImage: "/images/productEx.png",
    brand: "NaturaBliss",
    category: "Body Care",
    price: 22.5,
    isOnSale: false,
    description: `A deeply hydrating body oil blended with honey and almond extract. It leaves skin smooth and radiant with a sweet, warm scent.`,
  },
  {
    id: "31",
    productName: "Rose Quartz Facial Roller",
    slug: "Rose-Quartz-Facial-Roller",
    productImage: "/images/productEx4.png",
    brand: "GlowStone",
    category: "Hair Care",
    price: 25.0,
    isOnSale: true,
    description: `A luxury facial roller crafted from natural rose quartz. It helps reduce puffiness, boost circulation, and promote a youthful glow.`,
  },
  {
    id: "32",
    productName: "Midnight Oud Perfume Mist",
    slug: "Midnight-Oud-Perfume-Mist",
    productImage: "/images/productEx5.png",
    brand: "NoirEssence",
    category: "Fragrance",
    price: 36.5,
    isOnSale: true,
    description: `A bold and exotic fragrance with hints of oud, amber, and musk. Perfect for evening wear, exuding confidence and sophistication.`,
  },
  {
    id: "33",
    productName: "Daily Hydration Face Moisturizer",
    slug: "Daily-Hydration-Face-Moisturizer",
    productImage: "/images/productEx6.png",
    brand: "AquaLeaf",
    category: "Skincare (Face)",
    price: 19.99,
    isOnSale: false,
    description: `A lightweight daily moisturizer enriched with hyaluronic acid. It locks in moisture for soft, plump, and healthy-looking skin.`,
  },
  {
    id: "34",
    productName: "Satin Finish Foundation",
    slug: "Satin-Finish-Foundation",
    productImage: "/images/productEx7.png",
    brand: "VelviTone",
    category: "Makeup",
    price: 27.0,
    isOnSale: true,
    description: `A smooth, buildable foundation offering medium to full coverage. It blends seamlessly, leaving your skin with a natural satin finish.`,
  },
  {
    id: "35",
    productName: "Avocado Repair Hair Mask",
    slug: "Avocado-Repair-Hair-Mask",
    productImage: "/images/productEx8.png",
    brand: "NutriSilk",
    category: "Hair Care",
    price: 28.5,
    isOnSale: true,
    description: `A creamy hair mask enriched with avocado oil for deep nourishment. It strengthens and restores dry, damaged strands.`,
  },
  {
    id: "36",
    productName: "Tropical Breeze Shower Gel",
    slug: "Tropical-Breeze-Shower-Gel",
    productImage: "/images/productEx.png",
    brand: "OceanMist",
    category: "Body Care",
    price: 16.0,
    isOnSale: false,
    description: `A refreshing shower gel with tropical fruit extracts. It gently cleanses while leaving your skin smelling fresh and hydrated.`,
  },
  {
    id: "37",
    productName: "Soft Blend Makeup Sponge Set",
    slug: "Soft-Blend-Makeup-Sponge-Set",
    productImage: "/images/productEx2.png",
    brand: "ProBlend",
    category: "Beauty Tools",
    price: 14.75,
    isOnSale: true,
    description: `A set of two ultra-soft makeup sponges for flawless application. Suitable for blending liquid, cream, or powder products with ease.`,
  },
  {
    id: "38",
    productName: "Amber Noir Eau de Toilette",
    slug: "Amber-Noir-Eau-de-Toilette",
    productImage: "/images/productEx3.png",
    brand: "VelvetAura",
    category: "Fragrance",
    price: 42.0,
    isOnSale: false,
    description: `A sophisticated scent with warm amber and smoky undertones. Crafted for those who appreciate depth and elegance in every spray.`,
  },
  {
    id: "39",
    productName: "Green Clay Purifying Mask",
    slug: "Green-Clay-Purifying-Mask",
    productImage: "/images/productEx4.png",
    brand: "EarthGlow",
    category: "Skincare (Face)",
    price: 20.5,
    isOnSale: true,
    description: `A detoxifying clay mask designed to clear pores and control oil. Perfect for combination to oily skin types, leaving a smooth matte finish.`,
  },
  {
    id: "40",
    productName: "Tint & Glow BB Cream",
    slug: "Tint-&-Glow-BB-Cream",
    productImage: "/images/productEx5.png",
    brand: "SkinMuse",
    category: "Makeup",
    price: 22.0,
    isOnSale: false,
    description: `A lightweight BB cream that hydrates, blurs imperfections, and adds a natural glow. Ideal for achieving effortless everyday coverage.`,
  },
  {
    id: "41",
    productName: "Caffeine Infused Eye Cream",
    slug: "Caffeine-Infused-Eye-Cream",
    productImage: "/images/productEx6.png",
    brand: "BrightEyes",
    category: "Skincare (Face)",
    price: 24.99,
    isOnSale: true,
    description: `An energizing eye cream formulated with caffeine to reduce puffiness and dark circles. It instantly refreshes tired eyes for a well-rested look.`,
  },
  {
    id: "42",
    productName: "Sheer Blush Compact",
    slug: "Sheer-Blush-Compact",
    productImage: "/images/productEx7.png",
    brand: "RosyHue",
    category: "Makeup",
    price: 18.75,
    isOnSale: false,
    description: `A silky blush compact that adds a natural flush of color to your cheeks. The fine texture ensures smooth application and buildable intensity.`,
  },
  {
    id: "43",
    productName: "Mint & Tea Tree Scalp Scrub",
    slug: "Mint-&-Tea-Tree-Scalp-Scrub",
    productImage: "/images/productEx8.png",
    brand: "ScalpPure",
    category: "Hair Care",
    price: 26.0,
    isOnSale: true,
    description: `A refreshing scalp scrub with mint and tea tree oil to exfoliate buildup. It promotes a balanced, clean scalp and healthier hair growth.`,
  },
  {
    id: "44",
    productName: "Whipped Shea Body Soufflé",
    slug: "Whipped=Shea-Body-Soufflé",
    productImage: "/images/productEx.png",
    brand: "VelvaSkin",
    category: "Body Care",
    price: 23.0,
    isOnSale: true,
    description: `A luxuriously whipped body cream that melts into the skin. Enriched with shea butter for intense hydration and a silky finish.`,
  },
  {
    id: "45",
    productName: "Dual-Ended Eyeshadow Brush",
    slug: "Dual-Ended-Eyeshadow-Brush",
    productImage: "/images/productEx.png",
    brand: "Blendistry",
    category: "Hair Care",
    price: 13.5,
    isOnSale: false,
    description: `A professional-grade eyeshadow brush featuring two ends for blending and detailing. Crafted with ultra-soft bristles for smooth application.`,
  },
  {
    id: "46",
    productName: "Citrus Bloom Perfume Oil",
    slug: "Citrus-Bloom-Perfume-Oil",
    productImage: "/images/productEx.png",
    brand: "Essenza",
    category: "Fragrance",
    price: 29.5,
    isOnSale: true,
    description: `A delicate perfume oil with citrus, jasmine, and amber notes. The roll-on design makes it perfect for on-the-go fragrance touch-ups.`,
  },
  {
    id: "47",
    productName: "Hydra Balance Face Toner",
    slug: "Hydra-Balance-Face-Toner",
    productImage: "/images/productEx.png",
    brand: "PureTone",
    category: "Skincare (Face)",
    price: 18.5,
    isOnSale: false,
    description: `A gentle toner designed to balance pH levels and refine pores. Infused with chamomile and cucumber extracts for soothing hydration.`,
  },
  {
    id: "48",
    productName: "Luminous Cream Concealer",
    slug: "Luminous-Cream-Concealer",
    productImage: "/images/productEx.png",
    brand: "BrightVeil",
    category: "Makeup",
    price: 21.0,
    isOnSale: true,
    description: `A hydrating concealer that brightens under-eyes and conceals imperfections. The creamy formula blends effortlessly for a natural, radiant look.`,
  },
  {
    id: "49",
    productName: "Argan & Shea Repair Conditioner",
    slug: "Argan-&-Shea-Repair-Conditioner",
    productImage: "/images/productEx.png",
    brand: "HydraStrand",
    category: "Hair Care",
    price: 25.0,
    isOnSale: false,
    description: `A restorative conditioner infused with argan and shea butter. It smooths, strengthens, and enhances shine for softer, healthier hair.`,
  },
  {
    id: "50",
    productName: "Cocoa Bliss Hand Cream",
    slug: "Cocoa-Bliss-Hand-Cream",
    productImage: "/images/productEx.png",
    brand: "SoftPetal",
    category: "Body Care",
    price: 15.0,
    isOnSale: true,
    description: `A rich, non-greasy hand cream infused with cocoa butter for instant hydration. It leaves hands soft, smooth, and delicately scented.`,
  },
];
